[workspace]
default-members = [
  "qbox-core",
  "qbox-broker",
  "qbox-gui",
  "qbox-cli",
  "qbox-strategy",
]
members = [
  "qbox-core",
  "qbox-broker",
  "qbox-gui",
  "qbox-cli",
  "qbox-strategy",
]
